services:
  db:
    image: postgres:15.2-alpine
    ports:
      - "${PG_PORT:-5432}:5432"
    volumes:
      - unleash-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: unleash
      POSTGRES_PASSWORD: unleash
      POSTGRES_DB: unleash
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  unleash-data:
    driver: local
